### ISSUE TITLE
Minor bug and location mismatches

### ISSUE THREAD

**Issue by Laura-Alex** [IndexThePlanet/LoganSearch#1]
Hello!
Thank you for developing this program. I think it's a great idea.

My session:
https://logan-search.org/dashboard/kmviz-463e7997-64e3-47ab-938a-0b20730b128b

Spotted a very small bug in the email announcing the completion of my query. The issue is that the hyperlink leads to `https://logan-search.org/dashboard/kmviz-463e7997-64e3-47ab-938a-0b20730b128b'` instead of `https://logan-search.org/dashboard/kmviz-463e7997-64e3-47ab-938a-0b20730b128b` (so, there is an extra apostrophe at the end which breaks the hyperlink). Thought it might be useful to share.

Some of the location information on the map is wrong. I don't know if this is due to the original dataset being wrong, but thought I'd mention it. For example, dataset SRR14121689 is represented on the map somewhere in East Africa, and sample SRR14121648 in eastern north America, but checking this on the NCBI website, the samples appear to be from China. I can't exactly figure out why these two samples went awry, and others from the same bioproject (PRJNA717907) were fine.

All the best!

**Comment by almosnow** [comment]
Hi Laura, I'm the one behind the geo data inference,

Short answer:
Indeed those locations should be corrected, thank you for pointing those out!

Long answer:
The geocoding provider I used (AWS Here) is kind of bad, I would like to recompute the coordinates with a much better data source but that's on the backlog atm.

**Comment by Laura-Alex** [comment]
Understandable. Good luck with everything!

**Comment by tlemane** [comment]
Hi Laura,
Thank you for the report, the link issue will be fixed soon.
