### ISSUE TITLE
short sequence

### ISSUE THREAD

**Issue by RAWWiberg** [IndexThePlanet/LoganSearch#5]
Hi there,

I was recently made aware of LoganSearch, I love the idea! I have been looking for just such a tool for a little project I've had in the back of my mind for a long time.

Unfortunately my sequence of interest is short, just under the minimum limit of LoganSearch (at 28nt in length). Is there anything you can do to help me use it as a query across the SRA?

**Comment by pierrepeterlongo** [comment]
Logan-search is based on kmer searches, with k=31. Thus the lower limit is a query of size 31.
Also remind that logan search uses a index built with bloom filters, eg, with non-null false positive rate.  This can have a sensible effect when querying short sequences. See https://github.com/IndexThePlanet/LoganSearch/issues/4 for an example.
