### ISSUE TITLE
query failure

### ISSUE THREAD

**Issue by iwangtoknow** [IndexThePlanet/LoganSearch#6]
Dear Logan Team,

I received a query failure four times this morning.
For example kmviz-cac94a4d-afb1-42d1-9f32-2e7bae79ea8b, I am searching a sequence in the groups of Genomic_bacteria and Single_cell.

Cheers,

Wang

**Comment by pierrepeterlongo** [comment]
Hello Wang, 

Thank you for your message and sorry for the trouble. 
Could you share the queried sequence so that we can investigate the origin of the problem?

**Comment by tlemane** [comment]
Hello,
It is not related to your query. There was a config error on our side which is now fixed. You can resubmit.
Teo

**Comment by iwangtoknow** [comment]
Thanks!
