### ISSUE TITLE
Contigs/Unitigs Search results

### ISSUE THREAD

**Issue by iwangtoknow** [IndexThePlanet/LoganSearch#7]
Dear Logan Team,

On your web interface, there is a tab for Contigs/Unitigs Search, how could I obtain these results for all the IDs?
I believe there is no such info in the result.zip file, as when I load the session.json into my local kmviz, there is no such tab.
I would also like to have the contigs search function locally (http://localhost:8050/dashboard), if possible.

I am not sure I understand it correctly, when I select an ID and click the search button under the tab Contigs/Unitigs Search, does it search again in the specific ID? That means I could only obtain the contigs search results one by one for each of the IDs?

Cheers,

Wang

**Comment by tlemane** [comment]
Hello,

This function can only search one by one, and is only available in logan search and not in local instances.
But you can do the search yourself using [back_to_sequences](https://github.com/pierrepeterlongo/back_to_sequences) and the [Logan contigs/unitigs](https://github.com/IndexThePlanet/Logan).

Unitigs
```
curl https://s3.amazonaws.com/logan-pub/u/[accession]/[accession].unitigs.fa.zst | zstd -d | back_to_sequences --in-kmers your_query.fa --out-sequences result.fa
```

Contigs
```
curl https://s3.amazonaws.com/logan-pub/c/[accession]/[accession].contigs.fa.zst | zstd -d | back_to_sequences --in-kmers your_query.fa --out-sequences result.fa
```

Teo

**Comment by pierrepeterlongo** [comment]
Hello there, 

Additional info: documentation here https://github.com/IndexThePlanet/Logan/blob/main/Sequence_Search.md#method-2-back_to_sequences-tool indicates exactly how to proceed to do the search using back_to_sequences on logan contigs or unitigs. 

Pierre

**Comment by iwangtoknow** [comment]
Thanks Guys!
