### ISSUE TITLE
Groups classification

### ISSUE THREAD

**Issue by iwangtoknow** [IndexThePlanet/LoganSearch#8]
Dear Logan Team,

I tried a few searches, I used bacteria sequence and selected the Groups: GENOMICSINGLECELL_BCT GENOMIC_BCT(on 13th Nov.), but there are results from organisms indicated as eukaryotes. May I ask how were the groups classified?

Cheers,

Wang

**Comment by pierrepeterlongo** [comment]
Hello Wang.

Groups are created on the basis of the STAT results of each of the SRA accessions. https://pubmed.ncbi.nlm.nih.gov/34544477/

This classification is not perfect, some accessions may be wrongly assigned to groups they do not belong to. 

In case you really need to perform an exhaustive research, use the "all" field while selecting groups.

**Comment by iwangtoknow** [comment]
Thanks for the explanation.
